### PR TITLE
Implement half-price child discounts for all MAG events

### PR DESCRIPTION
**Pull request by kitsuta**
This code was in the magprime plugin, but both Stock and West leadership teams have requested this functionality so I'm copying it into our generic MAGFest plugin.

### CODE REVIEW

**Comment by RobRuana** [comment]
Does this mean that we also want to remove it from the magprime plugin?

**Comment by kitsuta** [comment]
Yeah, got distracted before filing that PR. :) One sec.

**Review by RobRuana — CHANGES_REQUESTED** [review]
Two things:

1. We probably also want to move over the model validations from: https://github.com/magfest/magprime/blob/9dd52a042d344419d9e41bc61e65fb7a468408f6/magprime/model_checks.py
2. Though this is not new code (just copied from one place to another) it would be nice to have some tests.

**Comment by kitsuta** [comment]
Whoops, forgot about this PR yesterday. Should be ready now.

Wait no, I forgot the tests! I'll do those now.

**Comment by kitsuta** [comment]
So, I'm not sure how to actually make the tests work.

It seems Wrong that we'd need to add all the scaffolding that the core plugin has. But based on the errors from the tests, that's what it wants? Do we really want to just copy the init_db function over to this plugin's conftest.py?

**Review by RobRuana — CHANGES_REQUESTED** [review]
Two things:

1. Wouldn't we want to move over all the validations in `model_checks.py`? See my other [PR review](https://github.com/magfest/magprime/pull/198#pullrequestreview-34869631)
2. Regarding tests, I am not a huge fan of how we set up our test DB sessions. You can get the tests running by adding this to `conftest.py`:
```
from uber.tests.conftest import *
```
I'll go through all the other plugins and add it so we don't run into the same issue in the future.

**Comment by kitsuta** [comment]
Whoops, why didn't I think of just importing conftests?

Tests are all updated and this should be ready.

**Review by RobRuana — APPROVED** [review]

**Pull request merged**
