### PR TITLE
Update treasury.html

### PR DESCRIPTION
**Pull request by bds002**
Update text per Craig / Treasuries Email.

### CODE REVIEW

**Comment by kitsuta** [comment]
Hm, can you put this in a new template in our magclassic repository? It has a bunch of event-specific stuff.

**Comment by bds002** [comment]
@binary1230  just set this stuff in a seperate MAGFest repository, I don;t know how to do what your asking.

**Comment by kitsuta** [comment]
Oh right, I was confused about which repository I was in, oops.

**Comment by binary1230** [comment]
it's minor and we can fix it later if there's actually any overlap, but you could use c.EVENT_NAME here instead of "magclassic" and the text will work when this is loaded in both the magprime uber and the maglabs uber

**Pull request merged**
